server:
  port: 8085

spring:
  application:
    name: andre.hermoza

  r2dbc:

    url: r2dbc:postgresql://ep-bitter-water-an498jl5-pooler.c-6.us-east-1.aws.neon.tech/andre_hermoza_12?sslmode=require
    username: neondb_owner
    password: npg_f2F7cmZsOzPt